spring.application.name=news-aggregator

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/newsdb
spring.datasource.username=postgres
spring.datasource.password=aryaAnita#22
spring.docker.compose.enabled=false
logging.level.org.springframework.security=DEBUG

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

#Port
server.port=8080

